
project:
  type: website
  output-dir: docs

website:
  title: "ESG"
  page-footer: 
    border: False
    center: 
      - "Copyright 2022, Tianjun Hou"
  search:
    location: navbar
    type: overlay
    copy-button: true
  navbar:
    collapse: false
    right:
      - icon: github
        href: https://github.com/TJ-HOU/ESG_Resources/
    left:
      - text: "Preprints"
        file: preprints.qmd
      - text: "Media"
        menu:
        - blogs.qmd
        - podcasts.qmd
        - videos.qmd
        - social-feeds.qmd
      - text: "Guidelines"
        menu:
        - policies.qmd
        - standards.qmd
        - esgindex.qmd
      - text: "Events"
        file: events.qmd
      - text: "Career"
        menu:
        - jobs.qmd
        - training.qmd
      - text: "Data"
        menu:
        - database.qmd

format:
  html:
    theme: sketchy
    css: styles.css
    toc: true

editor: visual

