---
title: "Preprints"
---

::: panel-tabset
## ArXiv

```{r echo=FALSE, results='asis'}
library(rvest)
arxiv.raw<-read_html("https://arxiv.org/search/advanced?advanced=&terms-0-operator=AND&terms-0-term=ESG&terms-0-field=abstract&terms-1-operator=NOT&terms-1-term=Economic+Scenario+Generators&terms-1-field=abstract&classification-economics=y&classification-physics_archives=all&classification-q_finance=y&classification-include_cross_list=include&date-filter_by=all_dates&date-year=&date-from_date=&date-to_date=&date-date_type=submitted_date&abstracts=show&size=50&order=")
# title
urltext<-arxiv.raw%>%html_elements(".is-5")%>%html_text2()
urltext<-noquote(urltext)
nodes<-arxiv.raw%>%html_nodes(".is-inline-block > a")
title<-paste0("<a href=", html_attr(nodes, "href"),">",urltext,"</a>")
# author
author<-arxiv.raw%>%html_elements(".authors , .authors .has-text-weight-semibold")%>%html_text2()
author<- gsub("^.{0,9}", "", author)
author<-author[author != ""]
author<-noquote(author)
# date
date<-arxiv.raw%>%html_elements(".abstract+ .is-size-7")%>%html_text2()
date <- gsub("^(.*?);.*", "\\1",date)
date<-sub(".*? ", "", date)
date<-noquote(date)
# create arxiv dataframe
arxiv <- data.frame(title,author,date)
library(DT)
datatable(arxiv, options = list(pageLength = 10),escape=FALSE, class = 'cell-border stripe')
```

## IDEAS

```{r echo=FALSE, results='asis'}
library(rvest)
library(stringr)
base_url<-"https://ideas.repec.org/cgi-bin/htsearch?form=extended&wm=wrd&dt=range&ul=%25%2Fa%2F%25&q=ESG&cmd=Search%21&wf=F000&s=R&db=01%2F01%2F2021&de=31%2F12%2F2022"
ideas_fun<-function(url){
  raw<-read_html(url)
  # date and author
  rawtext<-raw%>%html_elements("#content-block .list-group-item")%>%html_text2()
  author_date<-str_extract(rawtext, "[^:]+")
  date<-substr(author_date,nchar(author_date)-4, nchar(author_date)-1)
  author<-substr(author_date,1, nchar(author_date)-nchar(date)-3)
  date<-noquote(date)
  author<-noquote(author)
  # title
  nodes<-raw%>%html_nodes(".list-group-item a")
  urltext<-nodes%>%html_text(nodes)
  title<-paste0("<a href=", "https://ideas.repec.org",html_attr(nodes, "href"),">",urltext,"</a>")
  # create ideas dataframe
  res<-data.frame(title,author,date)
  return (res)
}
ideas<-ideas_fun(base_url) 
# loop over pages
i=1
tgt_url<- paste0(base_url,"&np=",i)
x<-read_html(tgt_url)%>%html_elements("#content-block .list-group-item")%>%html_text2()
while(!identical(x, character(0))){
  Sys.sleep(10)
  idea_temp<-ideas_fun(tgt_url)
  ideas<-rbind(ideas,idea_temp)
  i=i+1
  tgt_url<- paste0(base_url,"&np=",i)
  x<-read_html(tgt_url)%>%html_elements("#content-block .list-group-item")%>%html_text2()
}
library(DT)
datatable(ideas, options = list(pageLength = 10),escape=FALSE, class = 'cell-border stripe')
```

## SSRN

```{r echo=FALSE, results='asis',message=FALSE}
library(rvest)
library(DT)
library(tidyverse)
ssrn_fun<-function(url){
  raw<-read_html(url)
  # remove duplicate entry
  nodes<-raw%>%html_elements(".optClickTitle")
  urltext<-nodes%>%html_text(nodes)
  urltext<-gsub("\r", "", urltext)
  url<-html_attr(nodes, "href")
  date.raw<-raw%>%html_elements("#versions-tooltip .trow+ .trow .note-list span , .note-list span:nth-child(2)")%>%html_text2()
  date<-grep('Posted', date.raw, value=TRUE)
  date<- gsub("^.{0,8}", "", date)
  date<-noquote(date)
  # dataframe
  res<-data.frame(urltext,url,date)
  res_df<-res%>%
    mutate(duplicate=tolower(urltext))%>%
    distinct(duplicate,.keep_all=TRUE)%>%
    select(-duplicate)
  # add author
  author<-raw%>%html_nodes(".authors-list")%>%html_text2()
  author<-noquote(author)
  author<- gsub("\r", "", author)
  res_df$author<-author
  res_df$title<-paste0("<a href=", res_df$url,">",res_df$urltext,"</a>")
  res_df<- res_df%>%select(title, author,date)
  return (res_df)
}

url_pt1<-"https://papers.ssrn.com/sol3/JELJOUR_Results.cfm?npage="
url_pt2<-"&form_name=journalBrowse&journal_id=1959162&Network=no&lim=false"
i=1
base_url<-paste0(url_pt1,i,url_pt2)
ssrn<-ssrn_fun(base_url) 

datatable(ssrn, options = list(pageLength = 10),escape=FALSE, class = 'cell-border stripe')
```
:::
