---
title: "Social Feeds"
---

::: panel-tabset
## Twitter

```{r include=FALSE}
#install.packages("rtweet")
#install.packages("keyring")
library(rtweet)
library(tidyverse)
library(DT)
library(keyring)

# please use your own twitter api key
appname<-key_get("twittername","thou40")
apikey <-key_get("twitterkey","thou40")
apisecret<-key_get("twittersecret","thou40")
access_token<-key_get("twitter_ac_token","thou40")
access_secret <-key_get("twitter_ac_secret","thou40")

# create token named "twitter_token"
twitter_token <- create_token(
  app = appname,
  consumer_key = apikey,
  consumer_secret = apisecret,
  access_token = access_token,
  access_secret = access_secret)
# search for 500 tweets using the #rstats hashtag
esg_tweets <- search_tweets(q = "#ESG",n = 500)
colnames(esg_tweets)
selected_tweets<-esg_tweets%>%
  select(status_id,created_at,screen_name,text,retweet_count,favorite_count)%>%
  mutate(url=paste0("https://twitter.com/",screen_name,"/status/",status_id))%>%
  mutate(link=paste0("<a href=",url,">",text,"</a>"))%>%
  mutate(date=substr(created_at,1,10))%>%
  select(link,screen_name,date,retweet_count,favorite_count)

names(selected_tweets) <- c('Tweet','User','Date','Retweet_count', 'Favorite_count')
```

```{r echo=FALSE, results='asis'}
datatable(selected_tweets, options = list(pageLength = 10),escape=FALSE, class = 'cell-border stripe')
```

## Reddit

```{r include=FALSE}
#install.packages("reticulate")
library(reticulate)
#py_install("praw")
#py_install("pandas")
#py_install("keyring")
```

```{python include=FALSE}
import praw
import pandas as pd
import keyring

# please use your own reddit api key
id=keyring.get_password('reddit', 'id')
secret=keyring.get_password('reddit', 'secret')
agent=keyring.get_password('reddit', 'agent')

reddit = praw.Reddit(client_id=id,client_secret=secret,user_agent=agent)
posts = []
esg_subreddit = reddit.subreddit('EsgInvesting')
for post in esg_subreddit.hot(limit=100):
    posts.append([post.title, post.created, post.subreddit, post.permalink, post.num_comments, post.selftext])
posts = pd.DataFrame(posts,columns=['title','date','subreddit','url','num_comments','body'])
```

```{r include=FALSE}
reddit_raw<-py$posts
reddit_raw$Post<-paste0("<a href=https://www.reddit.com",
                        reddit_raw$url,">",reddit_raw$title,"</a>")
reddit_raw$Date<-format(as.POSIXct(reddit_raw$date, origin='1970-01-01'), format='%Y/%m/%d')
reddit_select<-reddit_raw%>%select(Post,Date,num_comments,body)
colnames(reddit_select) <- c("Post","Date","# of comments","Text")
```

```{r echo=FALSE, results='asis'}
library(DT)
datatable(reddit_select, options = list(pageLength = 10),escape=FALSE,class ='cell-border stripe')
```
:::
