---
title: "Videos (Under Maintenance)"
---

```{r include=FALSE,message=FALSE}
#remove.packages("reticulate")
#install.packages("reticulate")
library(reticulate)
#py_install("selenium")
#py_install("pandas")
```

```{python include=FALSE}
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.edge.service import Service
import time
import pandas as pd
s=Service(r"/Users/tj_hou/Downloads/edgedriver_mac64/msedgedriver")
driver = webdriver.Edge(service=s)
driver.get('https://www.youtube.com/results?search_query=esginvesting')
# ensure that the page is loaded
time.sleep(10)
# scrolling down the page 5 times
i=0
while (i<5) :
    driver.execute_script("var scrollingElement = (document.scrollingElement || document.body);scrollingElement.scrollTop = scrollingElement.scrollHeight;")
    time.sleep(1)
    i=i+1

    # once end element is located, break out of the loop
    end_result = driver.find_element_by_css_selector('#message').is_displayed()
    if end_result == True:
        break

# select data of videos
youtube_data = []
for result in driver.find_elements_by_css_selector('.text-wrapper.style-scope.ytd-video-renderer'):   
  title = result.find_element_by_css_selector('.title-and-badge.style-scope.ytd-video-renderer').text
  link = result.find_element_by_css_selector('.title-and-badge.style-scope.ytd-video-renderer a').get_attribute('href')
  channel_name = result.find_element_by_css_selector('.long-byline').text
  views = result.find_element_by_css_selector('.style-scope ytd-video-meta-block').text.split('\n')[0]
  time_published = result.find_element_by_css_selector('.style-scope ytd-video-meta-block').text.split('\n')[1]
  youtube_data.append({
    'title': title,
    'link': link,
    'channel': channel_name,
    'views': views,
    'time_published': time_published,
    })

driver.close()
df=pd.DataFrame(youtube_data)
```

```{r echo=FALSE, message=FALSE,,warning=FALSE,results='asis'}
library(DT)
library(tidyverse)
youtube<-py$df
### the hyperlink doesn't work on website, need to fix it ###
youtube$Title<-paste0("<a href=",youtube$link,">",youtube$title,"</a>")
youtube_select<-youtube%>%select(Title,channel,views,time_published)
colnames(youtube_select) <- c("Title","Channel","Time_published","Views")
datatable(youtube_select, options = list(pageLength = 10),escape=FALSE, class = 'cell-border stripe')
```
